# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab87e4af6893ca055e8af54db9ec9b43f289d406ed1211bac36edc22b00c3acc135f1c8633af37ca3d73a8873c310b4b028805bb50f852c8afdd763f0984262f
  auth_token: '0b4d9f21c882b46606d09e9c85c5eab9'

test:
  secret_key_base: 9441e4c34cf7a3726d9901b94f355b5ce301ca8e49fa40d86b2bba55600bf2c8d7a007a4952294094745583cbe2fa20d560ed6362780117ff7eaadf38cfe4bc5
  auth_token: '0b4d9f21c882b46606d09e9c85c5eab9'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_token: '0b4d9f21c882b46606d09e9c85c5eab9'

